### PR TITLE
Use composite condition for exceptions with lmdb error strings

### PR DESCRIPTION
**Pull request by caolan**
I wanted an easy way to detect missing keys, preferably using condition-case, so here's a patch to create (exn lmdb ...) style composite conditions. It also uses the LMDB string for the error code as the message.

I've not triggered an abort from C using define-external before, so I'd someone to review that first.

### CODE REVIEW

**Comment by iraikov** [comment]
Thanks for the patch, but I am also not sure about whether abort can be called from define-external. Would it not make sense  to pass the exception object as another argument to chicken_lmdb_exception and chicken_ThrowException? If not, could you ask on the mailing list whether abort in define-external is ok? Thanks!

**Comment by caolan** [comment]
Yes, I'll do some more investigation. Does the aim of the patch seem OK otherwise (adding composite conditions)?

**Comment by iraikov** [comment]
Yes, otherwise the patch seems OK, the CI test fails because for some
reason the lmdb package is not available for installation in the Travis
environment. Perhaps it would have to be compiled from source.

Ivan

**Comment by iraikov** [comment]
Hi Caolan, doesn't look like anybody responded to your post, so I went ahead and merged the pull request. Can you also add some unit tests for your condition-case use case?

**Comment by caolan** [comment]
@iraikov thanks, I'll look into updating the tests.

**Pull request merged**
